### ISSUE TITLE
Create a gif for Model Training Page

### ISSUE THREAD

**Issue by fakela** [mindee/documentation#3]
Create a gif for model training page for the docs

**Comment by fakela** [comment]
Here is a gif created for this https://www.kapwing.com/e/61aeac37ad39670148502f14?autoplay=true. I tried embedded it on README it didn’t work

**Comment by fharper** [comment]
Perfect, I'll update it, thanks

**Comment by fharper** [comment]
It's done, but I have to cut it so we only get the part about the model training since the file was too big. Even now, to be under README image size limit, I had to lower down the resolution which doesn't give a great animated gif... That will do it for now, but when we move to our own platform, we will do it again with a better quality.
